using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GrandCheese.Util
{
    public enum LoginOpcodes : short
    {
        HEART_BIT_NOT = 0,
        SET_SECURITY_KEY_NOT = 1,
        ENU_VERIFY_ACCOUNT_REQ = 2,
        ENU_VERIFY_ACCOUNT_ACK = 3,
        ENU_SERVER_LIST_NOT = 4,
        ENU_WAIT_TIME_NOT = 5,
        EVENT_CLOSE_CONNECTION_NOT = 6,
        ENU_CHANNEL_NEWS_NOT = 7,
        ENU_ITEM_BUY_INFO_NOT = 8,
        ENU_LOG_OUT_NOT = 9,
        ENU_CLIENT_SCRIPT_INFO_NOT = 10,
        ENU_CLIENT_CONTENTS_OPEN_NOT = 11,
        ENU_NEW_CLIENT_CONTENTS_OPEN_NOT = 12,
        ENU_SOCKET_TABLE_INFO_NOT = 13,
        ENU_OVERLAP_FILE_INFO = 14,
        ENU_GUIDE_BOOK_LIST_REQ = 15,
        ENU_GUIDE_BOOK_LIST_ACK = 16,
        ENU_TEXTURE_DYNAMIC_LOAD_REQ = 17,
        ENU_TEXTURE_DYNAMIC_LOAD_ACK = 18,
        ENU_LOADING_IMAGE_REQ = 19,
        ENU_LOADING_IMAGE_ACK = 20,
        ENU_CLIENT_CONTENTS_FIRST_INIT_INFO_REQ = 21,
        ENU_CLIENT_CONTENTS_FIRST_INIT_INFO_ACK = 22,
        ENU_CLIENT_PING_CONFIG_REQ = 23,
        ENU_CLIENT_PING_CONFIG_ACK = 24,
        ENU_SHAFILENAME_LIST_REQ = 25,
        ENU_SHAFILENAME_LIST_ACK = 26,
        ENU_STAY_SERVER_TIMEOUT = 27,
        ENU_SERVER_LOGIN_REQ = 28,
        ENU_USER_LOGIN_REQ = 29,
        ENU_USER_LOGOUT_REQ = 30,
        ENU_SERVER_HEART_BEAT_REQ = 31,
        ENU_USER_HEARTBEAT_REQ = 32,
        ENU_CYOU_CHANGE_CASH_REQ = 33,
        ENU_CYOU_CHANGE_CASH_ACK = 34,
        ENU_CYOU_GET_REMAIN_CASH_REQ = 35,
        ENU_CYOU_BUY_LOG_REQ = 36,
        ENU_USER_AGREEMENT_REQ = 37,
        ENU_CASHBACK_RATIO_INFO_NOT = 38,
        ENU_CLIENT_CONTENTS_FIRST_INIT_ADDITIONAL_INFO_REQ = 39,
        ENU_CLIENT_CONTENTS_FIRST_INIT_ADDITIONAL_INFO_ACK = 40,
        ENU_OVERLAPPED_FILE_LOG = 41,
        ENU_BLOCKIPUSER_CONN_LOG = 42,
        ENU_DB_QUEUE_SIZE_LOG = 43,
        ENU_CYOU_CHANGE_CASH_LOG = 44,
        ENU_TICK_MANAGER_LOG = 45,
    }
}
